<%option explicit%>
<!--METADATA TYPE="typelib" FILE="\Program Files\Common Files\System\ado\msado15.dll"-->
<!--#INCLUDE VIRTUAL="/genergy2/nonsecure.inc"-->
<%
'if not(allowGroups("Genergy Users")) then
'%><%
'end if
%>

<html>
	<head>
		<style>
		</style>
	</head>
	<body>
		<table>
			<tr>
				<td>RNEEMBKA</td>
				<td>Embankments</td>
				<td>
					<tr>
						<td>water</td>
					</tr>
					<tr>
						<td>elec</td>
					</tr>
						<tr>
						<td>steam</td>
					</tr>
					<tr>
						<td>gas</td>
					</tr>					
				</td>
				<td>
					<tr>
						<td>water</td>
					</tr>
					<tr>
						<td>elec</td>
					</tr>
						<tr>
						<td>steam</td>
					</tr>
					<tr>
						<td>gas</td>
					</tr>					
				</td>
				<td>
					<tr>
						<td>water</td>
					</tr>
					<tr>
						<td>elec</td>
					</tr>
						<tr>
						<td>steam</td>
					</tr>
					<tr>
						<td>gas</td>
					</tr>					
				</td>
				<td>
					<tr>
						<td>water</td>
					</tr>
					<tr>
						<td>elec</td>
					</tr>
						<tr>
						<td>steam</td>
					</tr>
					<tr>
						<td>gas</td>
					</tr>					
				</td>
				<td>
					<tr>
						<td>water</td>
					</tr>
					<tr>
						<td>elec</td>
					</tr>
						<tr>
						<td>steam</td>
					</tr>
					<tr>
						<td>gas</td>
					</tr>					
				</td>				
			</tr>
		</table>
	</body>
</html>